### ISSUE TITLE
Comparison with saltine

### ISSUE THREAD

**Issue by Bodigrim** [haskell-cryptography/cryptography-libsodium-bindings#10]
What's the relationship of this project to https://hackage.haskell.org/package/saltine? It seems goals are pretty much the same, no?

**Comment by Bodigrim** [comment]
One more: https://hackage.haskell.org/package/libsodium-1.0.18.1
It would be nice to clarify in README, how this initiative is different.

**Comment by Bodigrim** [comment]
@Kleidukos ping.

**Comment by Kleidukos** [comment]
Hi @Bodigrim, thanks for the reminder. :)

**Comment by kozross** [comment]
@Bodigrim Does the newly-modified README address your questions?
